apiVersion: integration/v1
kind: Step
name: run
version: 1
summary: Run another Relay workflow

description: |
  Runs another workflow in your Relay account by its name.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/workflow-step-run

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Start the workflow `my-workflow` with `parameters`.
  content:
    apiVersion: v1
    kind: Step
    name: my-workflow
    image: relaysh/workflow-step-run
    spec:
      name: my-workflow
      parameters:
        message: "a message for my-workflow to print"
- summary: >
    Run the workflow `my-workflow` in a loop for every
    object in `parameterSets` as `parameters`.
  content:
    apiVersion: v1
    kind: Step
    name: my-workflow
    image: relaysh/workflow-step-run
    spec:
      name: my-workflow
      parameterSets:
        - message: "first message for my-workflow to print"
        - message: "second message for my-workflow to print"
        - message: "third message for my-workflow to print"
